<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.weeder.WEEDERTests-20210730163805" tests="7" file="tests/weeder.py" time="25.208" timestamp="2021-07-30T16:38:36" failures="1" errors="0" skipped="0">
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_default_voltage_THEN_get_default_voltage_correctly" time="0.844" timestamp="2021-07-30T16:38:11" file="tests\weeder.py" line="56"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_padding_THEN_get_padding_correctly" time="0.951" timestamp="2021-07-30T16:38:12" file="tests\weeder.py" line="46"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_scurve_ramping_voltage_THEN_get_ramping_voltage_correctly" time="0.802" timestamp="2021-07-30T16:38:33" file="tests\weeder.py" line="43"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_trapezoid_ramping_voltage_THEN_get_ramping_voltage_correctly" time="0.939" timestamp="2021-07-30T16:38:34" file="tests\weeder.py" line="40"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_voltage_THEN_get_voltage_back_correctly" time="1.007" timestamp="2021-07-30T16:38:35" file="tests\weeder.py" line="37"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_wait_THEN_get_wait_correctly" time="0.464" timestamp="2021-07-30T16:38:36" file="tests\weeder.py" line="52"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_ramp_rate_THEN_get_ramp_rate_correctly" time="20.201" timestamp="2021-07-30T16:38:33" file="tests\weeder.py" line="49">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1799:WEEDER_01:RAMPRATE' to have value '100' (type: 'int').
Final PV value was '10000.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\weeder\master\system_tests\tests\weeder.py", line 50, in test_WHEN_set_ramp_rate_THEN_get_ramp_rate_correctly
    self.ca.assert_setting_setpoint_sets_readback(100, "RAMPRATE")
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 554, in assert_setting_setpoint_sets_readback
    self.assert_that_pv_is(readback_pv, expected_value, timeout=timeout)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1799:WEEDER_01:RAMPRATE' to have value '100' (type: 'int').
Final PV value was '10000.0' (type: 'float')
]]></failure>
	</testcase>
</testsuite>
